name: flyde
description: A C++ workflow tool for the command line
repository: https://github.com/Coronon/flyde
version: 1.0.0
homepage: https://github.com/Coronon/flyde

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^2.0.5
  hive_generator: ^1.1.0

dependencies:
  crypto: ^3.0.1
  json_serializable: ^4.1.3
  path: ^1.8.0
