name: flyde
description: A C++ workflow tool for the command line
repository: https://github.com/Coronon/flyde
version: 1.0.0
homepage: https://github.com/Coronon/flyde

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
