name: flyde
description: A C++ workflow tool for the command line
repository: https://github.com/Coronon/flyde
version: 1.0.0
homepage: https://github.com/Coronon/flyde

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
