name: flyde
description: A C++ workflow tool for the command line
repository: https://github.com/Coronon/flyde
version: 1.0.0
homepage: https://github.com/Coronon/flyde

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  json_annotation: ^4.1.0
  path: ^1.8.0
  crypto: ^3.0.1
  cryptography: ^2.0.2
  synchronized: ^3.0.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
  json_serializable: ^5.0.0
  build_runner: ^2.0.6
  http: ^0.13.3
